apiVersion: apps/v1
kind: Deployment
metadata:
  name: coustomer
  labels:
    app: coustomer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coustomer
  template:
    metadata:
      labels:
        app: coustomer
    spec:
      containers:
        - name: coustomer
          image: username/coustomer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5